version: '3'
services:
  chat-extractor:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
      IP: ${IP}
    volumes:
      - ./data:/usr/src/app/data
      - ./session_name.session:/usr/src/app/session_name.session
      - ./contracts.json:/usr/src/app/contracts.json
      - ./sent_contracts.json:/usr/src/app/sent_contracts.json
    command: flask run --host=0.0.0.0 --port=${PORT}
